updated bugs sh handling

diff --git a/mythicalLibrarian b/mythicalLibrarian
--- a/mythicalLibrarian
+++ b/mythicalLibrarian
@@ -3,7 +3,7 @@
 # ***** WELCOME! Scroll further down to set the user settings. *****
 
  #mythicalLibrarian by Adam Outler
- #Wed, 30Jan2010 1023
+ #Wed, 18FEB2010 1753
  #email: outleradam@hotmail.com
  #Software the way it should be: Free and Open Source
  #Please contact me with any bug reports 
@@ -147,7 +147,7 @@
  #Guide data type
  GuideDataType=SchedulesDirect
  #MySQL User name: Default="mythtv"
- MySQLuser="mythtv" #<------THIS VALUE MUST BE SET-------
+ MySQLuser="mythtv" 
  #MySQL Password: Default="mythtv"
  MySQLpass="mythtv" #<------THIS VALUE MUST BE SET-------
  #MySQL Myth Database: Default="mythconverg"
@@ -178,10 +178,12 @@
  XBMCNotify=Enabled
  #Ip Address and port for XBMC Notifications Eg.XBMCIPs=( "192.168.1.110:8080" "192.168.1.111:8080" "XBOX:8080" )
  XBMCIPs=( "192.168.1.110:8080" "XBOX:8080" ) #<------THIS VALUE MUST BE SET-------
- #Commands to be run on sucessful job
+ #maxItems controls the number of items in the RSS. RSS Can be activated by creating a folder in /var/www/mythical-rss.  
+ maxItems=8  
 
  #########################USER SETTINGS##########################
  ########################## USER JOBS############################
+ #The RunJob function is a place where you can put your custom script to be run at the end of execution
  RunJob () {
  	case $jobtype in
  #Sucessful Completion of mythicalLibrarian
@@ -192,22 +194,24 @@
  			#
  			exit 0
  			;;
- #File system error occoured
- 		PermissionError0Length|InvalidFileNameSupplied|PermissionErrorWhileMoving|FailSafeModeComplete|LinkModeFailed)
- 			echo "FILE SYSTEM ERROR:$jobtype"
- 			#Insert Custom User Job here 
- 			
- 			#
-   			exit 1
- 			;;
- 
+
  #Information error occoured
  		TvDbIsIncomplete|GenericShow)
  			echo "INSUFFICIENT INFORMATION WAS SUPPLIED:$jobtype"
   			#Insert Custom User Job here 
  			
  			#
-  			exit 2
+  			exit 0
+ 			;;
+
+  #File system error occoured
+ 		PermissionError0Length|InvalidFileNameSupplied|PermissionErrorWhileMoving|FailSafeModeComplete|LinkModeFailed)
+ 			echo "FILE SYSTEM ERROR:$jobtype"
+ 			#Insert Custom User Job here 
+ 			
+ 			#
+   			exit 1
+
  			;;
  #Generic error occoured
   		GenericUnspecifiedError)
@@ -215,15 +219,14 @@
   			#Insert Custom User Job here  
  			
  			#
-  			exit 3 
+  			exit 2 
  			;;
   esac
  #Custom exit point may be set anywhere in program by typing RunJob on any new line
  #Insert Custom User Job here 
  
  #
- exit 4
-
+ exit 3
  }
  
  ########################## USER JOBS############################
@@ -242,6 +245,7 @@
  		reporttime=`date +%T`
      		echo "$reporttime "$InputTitle>>"$mythicalLibrarian/DailyReport/$reportfilename"
  	fi
+ 	return 0
  }
   
  #####CHECK PERMISSIONS#####
@@ -249,20 +253,21 @@
  #CheckPermissions takes file size, free space on dir, and the dir, then it performs
  #tests.  the result will be $TMoveDirWritable as a 1 or a 0 for writable or not.
  checkpermissions () { 
- TMoveDirWritable=0
- if [ "$2" != "" ] && [ "$1" != "" ] && [ $1 -lt $2 ]; then
- 	echo "Testing write permission on $3">$3/arbitraryfile.ext 
- 	if [ -f "$3/arbitraryfile.ext" -a -s "$3/arbitraryfile.ext" ]; then
- 		rm -f "$3/arbitraryfile.ext"
- 		test ! -f "$3/arbitraryfile.ext" && TMoveDirWritable=1 || TMoveDirWritable=0
- 	else
- 		TMoveDirWritable=0
- 		echo "CHECK PERMISSIONS ON $MoveDir"
- 	fi
- elif [ -z "$2" ] || [ $1 -ge $2 ]; then
  	TMoveDirWritable=0
- 	echo "UNUSABLE SPACE-CHECK:$3"
- fi
+ 	if [ "$2" != "" ] && [ "$1" != "" ] && [ $1 -lt $2 ]; then
+ 		echo "Testing write permission on $3">$3/arbitraryfile.ext 
+ 		if [ -f "$3/arbitraryfile.ext" -a -s "$3/arbitraryfile.ext" ]; then
+ 			rm -f "$3/arbitraryfile.ext"
+ 			test ! -f "$3/arbitraryfile.ext" && TMoveDirWritable=1 || TMoveDirWritable=0
+ 		else
+ 			TMoveDirWritable=0
+ 			echo "CHECK PERMISSIONS ON $MoveDir"
+ 		fi
+ 	elif [ -z "$2" ] || [ $1 -ge $2 ]; then
+ 	 	TMoveDirWritable=0
+	 	echo "UNUSABLE SPACE-CHECK:$3"
+	fi
+ 	return 0
  }
  
  #####FUZZY LOGIC RECOGNITION OF SERIES#####
@@ -276,27 +281,30 @@ echo $showname
  #Get the seriesid based on the showname
   	seriesid=`sed -n $serieslinenumber'p' "$mythicalLibrarian"/sid.txt| grep -m1 ^`
  	NewShowName=`sed -n $serieslinenumber'p' "$mythicalLibrarian"/shn.txt|replace "&amp" "&"| tr -d '"<>:!\|/'|grep -m1 ^`
+ 	return 0
  }
 
  #####COMSKIP FILES#####
  #Function GenComSkip creates a comskip.txt file for use with the show upon moving, created from data from library
  GenComSkip () {
- 		mythicalLibrarianCounter=1
+ 	mythicalLibrarianCounter=1
+ 
  #Set up comskip file
- 		test -f "$mythicalLibrarian/markupframes.txt" && rm -f "$mythicalLibrarian/markupframes.txt"
- 		echo "FILE PROCESSING COMPLETE">"$mythicalLibrarian"/markupframes.txt
- 		echo "------------------------">>"$mythicalLibrarian"/markupframes.txt	
- 		while read line
- 			do
- 			mythicalLibrarianCounter=`expr $mythicalLibrarianCounter + 1`;
- 			StartData=`sed -n "$mythicalLibrarianCounter"p "$mythicalLibrarian/markupstart.txt"`
- 			StopData=`sed -n "$mythicalLibrarianCounter"p "$mythicalLibrarian/markupstop.txt"`
- 			if [ ! -z "$StopData" ]; then
- 				echo "$StartData $StopData">>"$mythicalLibrarian"/markupframes.txt
- 				CommercialMarkup="Created"
- 				echo "COMMERCIAL DATA START:$StartData STOP:$StopData"
- 			fi
- 		done <"$mythicalLibrarian/markupstop.txt"
+ 	test -f "$mythicalLibrarian/markupframes.txt" && rm -f "$mythicalLibrarian/markupframes.txt"
+ 	echo "FILE PROCESSING COMPLETE">"$mythicalLibrarian"/markupframes.txt
+ 	echo "------------------------">>"$mythicalLibrarian"/markupframes.txt	
+ 	while read line
+ 		do
+ 		mythicalLibrarianCounter=`expr $mythicalLibrarianCounter + 1`;
+ 		StartData=`sed -n "$mythicalLibrarianCounter"p "$mythicalLibrarian/markupstart.txt"`
+ 		StopData=`sed -n "$mythicalLibrarianCounter"p "$mythicalLibrarian/markupstop.txt"`
+ 		if [ ! -z "$StopData" ]; then
+ 			echo "$StartData $StopData">>"$mythicalLibrarian"/markupframes.txt
+ 			CommercialMarkup="Created"
+ 			echo "COMMERCIAL DATA START:$StartData STOP:$StopData"
+ 		fi
+ 	done <"$mythicalLibrarian/markupstop.txt"
+ 	return 0
  }
  
  
@@ -309,15 +317,15 @@ echo $showname
  #Send notification to XBMC, Update Library, Clean Library
  
  if [ "$XBMCNotify" = "Enabled" ] || [ "$XBMCUpdate" = "Enabled" ] || [ "$XBMCClean" = "Enabled" ]; then
- 
- 	for XBMCIP in ${XBMCIPs[@]}
+  	for XBMCIP in ${XBMCIPs[@]}
  	do
  		echo "SENDING REQUESTED COMMANDS TO:$XBMCIP"
  		test "$XBMCNotify" = "Enabled" && curl -s -m1 "http://"$XBMCIP"/xbmcCmds/xbmcHttp?command=ExecBuiltIn(Notification(mythical%20Librarian%2Cadding%20show%20$tvdbshowname%20to%20library))" > /dev/null 2>&1
  		test "$XBMCUpdate" = "Enabled" && curl -s -m1 "http://"$XBMCIP"/xbmcCmds/xbmcHttp?command=ExecBuiltIn(UpdateLibrary(video))" > /dev/null 2>&1
  		test "$XBMCClean" = "Enabled" && curl -s -m1 "http://"$XBMCIP"/xbmcCmds/xbmcHttp?command=ExecBuiltIn(CleanLibrary)" > /dev/null 2>&1
  	done
- fi
+ 	fi
+ 	return 0
  }
  
  
@@ -442,15 +450,16 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  #####INITIAL DATASE GRAB#####
  ##This function grabs title and subtitle from the database for use in the rest of the script
  GrabTitleAndSubtitle () {
- if [ "$InputTitle" = "" ]; then
+ 	if [ "$InputTitle" = "" ]; then
  
- 	InputTitle=`mysql -u$MySQLuser -p$MySQLpass -e "use '$MySQLMythDb' ; select title from recorded where basename like '$InputFileBasename'; "|replace "airdate" ""|sed -n "2p"`
+ 		InputTitle=`mysql -u$MySQLuser -p$MySQLpass -e "use '$MySQLMythDb' ; select title from recorded where basename like '$InputFileBasename'; "|replace "airdate" ""|sed -n "2p"`
 
      #get year for movies 
- 	InputSubtitle=`mysql -u$MySQLuser -p$MySQLpass -e "use '$MySQLMythDb' ; select subtitle from recorded where basename like '$InputFileBasename' ; "|replace "Subtitle" ""|sed -n "2p"`
+ 		InputSubtitle=`mysql -u$MySQLuser -p$MySQLpass -e "use '$MySQLMythDb' ; select subtitle from recorded where basename like '$InputFileBasename' ; "|replace "Subtitle" ""|sed -n "2p"`
 
 
- fi
+ 	fi
+ 	return 0 
  }
  #####MYTHTV DATABASE#####
  #This function gathers information from the mythtv database for use in the program
@@ -509,7 +518,7 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
 
  		GenComSkip
  	fi
-
+ 	return 0
  }
  
  #####REMOVE ENTRIES FROM LIBRARY#####
@@ -527,6 +536,7 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  #Remove thumbnails
  		rm -f "$originaldirname/$FileBaseName".*	
  	fi 
+ 	return 0
  }
  
  
@@ -551,6 +561,7 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
 	test "$mythicalLibrarianProgramIDCheck" = "EP" && ProgramIDType="Series With Episode Data"
  
  	Zap2itSeriesID=`echo $ProgramID| tr -d MVSHEP | sed 's/0*//' | sed 's/.\{4\}$//' `
+ 	return 0 
  }
 
  #####DOWNLOAD AND PARSE INFORMATION FROM THETVDB#####
@@ -640,33 +651,39 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  		echo "DATABASE IS MAINTAINED. TIME IS:$TvDbTime NEXT UPDATE IS:$LastUpdated"
  	fi
  fi
+ 	return 0
  }
  
  #####GENERATE tvshow.nfo#####
- tvshowNFO () {
- 	echo"<tvshow>">"$MoveDir"/tvshow.nfo
- 	echo"	<title>$NewShowName</title>">>"$MoveDir"/tvshow.nfo
- 	echo"	<rating>$rating/rating>">>"$MoveDir"/tvshow.nfo
- 	echo"	<season>-1</season>">>"$MoveDir"/tvshow.nfo
- 	echo"	<episode>0</episode>">>"$MoveDir"/tvshow.nfo
- 	echo"	<displayseason>-1</displayseason>">>"$MoveDir"/tvshow.nfo
- 	echo"	<displayepisode>-1</displayepisode>">>"$MoveDir"/tvshow.nfo
- 	echo"	<genre>$category<genre>">>"$MoveDir"/tvshow.nfo
- 	echo"</tvshow>">>"$MoveDir"/tvshow.nfo
+ GenerateTVShowNFO () {
+
+ 	if [ "$mythicalLibrarianProgramIDCheck" = "SH" -a ! -f "$Movedir/tvshow.nfo" ] || [ "$mythicalLibrarianProgramIDCheck" = "EP" ]; then
+		test -f "$MoveDir/tvshow.nfo" && rm "$MoveDir/tvshow.nfo"
+ 		echo -e "<tvshow>">>"$MoveDir"/tvshow.nfo
+ 		echo -e "\t<title>$NewShowName</title>">>"$MoveDir/tvshow.nfo"
+  		test "$ShowCategory" != "" && echo -e "\t<genre>$ShowCategory<genre>">>"$MoveDir/tvshow.nfo"
+ 		
+ 		echo -e "</tvshow>">>"$MoveDir/tvshow.nfo"
+ 	fi
+ return 0 
  } 
  
 #Create an NFO file based upon extracted information
- GenShowNFO () {
- 	test "$mythicalLibrarianProgramIDCheck" = "SH" && echo "<tvshow>">$mythicalLibrarian/NFOFILE.NFO
- 	test "$mythicalLibrarianProgramIDCheck" = "SH" && echo "      <title>$ShowName</title>">>"$mythicalLibrarian"/NFOFILE.NFO
- 	test "$mythicalLibrarianProgramIDCheck" = "SH" && echo "      <episodeguide>http://www.thetvdb.com/api/$APIkey/series/$seriesid/all/$Language.zip<episodeguide>">>"$mythicalLibrarian"/NFOFILE.NFO
- 	test "$mythicalLibrarianProgramIDCheck" = "SH" && echo "      <rating>$rating</rating>">>"$mythicalLibrarian"/NFOFILE.NFO
- 	test "$mythicalLibrarianProgramIDCheck" = "SH" && echo "      <plot>$plot</plot>">>"$mythicalLibrarian"/NFOFILE.NFO
- 	test "$mythicalLibrarianProgramIDCheck" = "SH" && echo "      <genre>$ShowCategory</genre>">>"$mythicalLibrarian"/NFOFILE.NFO
- 	test "$mythicalLibrarianProgramIDCheck" = "SH" && echo "      <premiered>$OriginalAirDate<aired>">>"$mythicalLibrarian"/NFOFILE.NFO
- 	test "$mythicalLibrarianProgramIDCheck" = "SH" && echo "      <recordstart>$ShowStartTime</recordstart>">>"$mythicalLibrarian"/NFOFILE.NFO
- 	test "$mythicalLibrarianProgramIDCheck" = "SH" && echo "</tvshow>">>"$mythicalLibrarian"/NFOFILE.NFO
-  }
+ GenerateEpisodeNFO () {
+ 	if [ "$mythicalLibrarianProgramIDCheck" = "SH" ]; then
+ 		test -f "$MoveDir/$ShowFileName.nfo" && rm "$MoveDir/$ShowFileName.nfo"
+ 		echo -e "<tvshow>">>"$MoveDir/$ShowFileName.nfo"
+ 		echo -e "\t<title>Recorded $datehour -Generic Episode</title>">>"$MoveDir/$ShowFileName.nfo"
+ 		echo -e "\t\t<rating>$rating</rating>">>"$MoveDir/$ShowFileName.nfo"
+ 		echo -e "\t<plot>$plot</plot>">>"$MoveDir/$ShowFileName.nfo"
+ 		echo -e "\t<genre>$ShowCategory</genre>">>"$MoveDir/$ShowFileName.nfo" 
+		echo -e "\t<season>0</season>">>"$MoveDir/$ShowFileName.nfo" 
+ 		echo -e "\t<episode>0</episode>">>"$MoveDir/$ShowFileName.nfo" 
+ 		echo -e "</tvshow>">>"$MoveDir/$ShowFileName.nfo"
+  		echo "'$MoveDir/$ShowFileName.nfo'" "'$MoveDir/$ShowFileName.$originalext'">>"$mythicalLibrarian"/created.tracking
+  	fi
+ 	return 0
+ }
 
  
  ########## END FUNCTIONS HERE ##########
@@ -683,7 +700,7 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  fi
 
  echo "@@@@@@@@@@@NEW SEARCH INITIATED AT `date`@@@@@@@@@@@@@">>"$mythicalLibrarian"/output.log 
-
+ showcheck="Enabled"
  #Set episode name, dir, extension, and showname from the input parameters.
  InputTitle=$2
  InputSubtitle=$3
@@ -699,7 +716,7 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  #Check for show translations relating to the show in question.
  if [ -f $mythicalLibrarian/showtranslations ]; then 
  	showtranslation=`grep "$ShowName = " "$mythicalLibrarian/showtranslations"|replace "$ShowName = " ""|replace "$mythicalLibrarian/showtranslations" ""`		 
- 	if [ "$showtranslation" != "$null" ];then 
+ 	if [ "$showtranslation" != "" ];then 
  		ShowName=$showtranslation
  		echo "USER TRANSLATION: $InputTitle = $ShowName">>"$mythicalLibrarian"/output.log
  	elif [ "$showtranslation" = "" ];then
@@ -754,11 +771,12 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  	do
  		DirToCheck=$line
  		if [ -d "$DirToCheck" ]; then
-  			DirToCheckCheck=`ls "$line"|grep -m1 ^`
+  			DirToCheckCheck=`ls "$line"|replace "tvshow.nfo" ""|grep -m1 ^`
 		 	if [ "$DirToCheckCheck" = "" ]; then
  				echo "REMOVING ORPHAN FOLDER:$line">>"$mythicalLibrarian"/output.log
   				echo "REMOVING ORPHAN FOLDER:$line"
- 				rmdir "$line"
+ 				test -f "$line/tvshow.nfo" && rm -f "$line/tvshow.nfo"
+				rmdir "$line"
 			elif [ "$DirToCheckCheck" != "" ]; then
   				echo "$DirToCheck" >> "$mythicalLibrarian/dir.tracking2"
 			fi
@@ -996,18 +1014,31 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  
 
  #####OUTPUT FILE NAME FORMATTING#####
- #format names for file system
+
+ #Format Shows
  epn=`echo $epn| tr -d [:punct:]`
  NewShowName=`echo $NewShowName|tr -d [:punct:]`
- #output Series format  showname=show name sxx=season number exx=episode number epn=episode name
+ Showname=`echo $ShowName|tr -d [:punct:]`
+ seasonyear=`date +%Y`
+ datehour=echo "`date +%Y%m%d%H%M`"
+ #Format Episodes showname=show name sxx=season number exx=episode number epn=episode name
  if [ ! -z "$exx" ]; then
  	 ShowFileName=`echo "$NewShowName.$sxx$exx ($epn)"`
 
- #output Movie Format
+
+
+ #Format Movies
  elif [ "$mythicalLibrarianProgramIDCheck" = "MV" ]; then
   	ShowFileName=`echo "$NewShowName ($MovieAirDate)"` 
  	MoveDir="$PrimaryMovieDir"
  	exx="Movie"
+
+ #Format generic Shows
+ elif [ "$mythicalLibrarianProgramIDCheck" = "SH" ]; then
+ 	ShowFileName=`echo "$ShowName.S$seasonyear""E00 (Recorded $datehour)"`
+	NewShowName=`echo $ShowName|tr -d [:punct:]`
+  	exx="Generic"
+ 	echo wootw
  fi
  
 
@@ -1022,10 +1053,9 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  	echo "%%%%%%%%%%%%%%OPERATION FAILED" `date` "%%%%%%%%%%%%%%%%%">>"$mythicalLibrarian"/output.log
  	echo  "mythicalLibrarian '$1' '$2' '$3'">>$mythicalLibrarian/doover.sh
  	echo "ERROR: INFORMATION COULD NOT BE OBTAINED"
- 	jobtype=TvDbIsIncomplete
+  	jobtype=TvDbIsIncomplete
  	RunJob
  fi
-  
  #check to see if output folder exists
  test -d "$MoveDir" && echo "SET TARGET DIR AS: $MoveDir"
  
@@ -1090,14 +1120,14 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  	done
   
  fi
- 
+
 
  #For debugging purposes only
- test "`basename $3`" = "testfile.ext" && exit 0
+ test "$InputPath" = "testfile.ext" && exit 0
  
  #####SH Identification Type Handling #####
  #if the ProgramID does not meet criteria, then end the program
- 	if [ "$ProgramIDType" = "Generic Episode With No Data" ]; then
+ 	if [ "$ProgramIDType" = "Generic Episode With No Data" -a "$showcheck" = "Enabled" ]; then
  		echo "GENERIC GUIDE DATA WAS SUPPLIED TYPE: $ProgramIDType- $InputTitle, $InputSubtitle">>"$mythicalLibrarian"/output.log
  		echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%">>"$mythicalLibrarian"/output.log
  		echo "%%%%%%%%%%%%%%%%%%%PROGRAM GUIDE DATA IS NOT COMPLETE%%%%%%%%%%%%%%%%%%%%">>"$mythicalLibrarian"/output.log
@@ -1106,7 +1136,7 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  		test $Notify = "Enabled" &&	sudo -u "$NotifyUserName" /usr/local/bin/librarian-notify-send "mythicalLibrarian Guide error" "Could not obtain enough information for library: $InputTitle $ProgramIDType" utilities-system-monitor
   		echo "mythicalLibrarian '$1' '$2' '$3'">>$mythicalLibrarian/doover.sh
   		jobtype=GenericShow
- 		RunJob
+		RunJob
  	fi
  #####MOVE MODE HANDLING#####
  #If symlink is not in LINK mode, Move and rename the file.
@@ -1134,12 +1164,19 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  			if [ "$SYMLINK" = "MOVE" ]; then
  				echo CREATING SYMLINK IN MOVE MODE
  				ln -s  "$MoveDir/$ShowFileName.$originalext" "$InputPath"
+ 				if [ ! -f  "$InputPath" ] ; then
+ 					test ! -f "$mythicalLibrarian"/undo.sh && echo "rm $mythicalLibrarian/undo.sh" >> "$mythicalLibrarian/undo.sh"
+ 					echo  "mv '$MoveDir/$ShowFileName.$originalext' '$InputPath'">>"$mythicalLibrarian/undo.sh"
+ 				else 
+ 					test ! -f "$mythicalLibrarian"/undo.sh && echo "rm $mythicalLibrarian/undo.sh" >> "$mythicalLibrarian/undo.sh"
+ 					echo  "#mv '$MoveDir/$ShowFileName.$originalext' '$InputPath'">>"$mythicalLibrarian/undo.sh"
+ 				fi
   			fi
-  			 test "$SYMLINK" = "Disabled" && SYMLINKDisabled 
+  			test "$SYMLINK" = "Disabled" && SYMLINKDisabled 
  #Send notification of completion and exit
  			test $Notify = "Enabled" && sudo -u "$NotifyUserName" /usr/local/bin/librarian-notify-send "mythicalLibrarian Sucess" "$ShowFileName moved to $MoveDir" info
- 	
- #Send notification to daily report log
+ 			GenerateTVShowNFO  
+ 			GenerateEpisodeNFO 
  			dailyreport "$ShowFileName"
  		 	echo "@@@@@@@@@@@@@OPERATION COMPLETE" `date` "@@@@@@@@@@@@@@@@">>"$mythicalLibrarian"/output.log
 			generaterss 
@@ -1168,14 +1205,16 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  		RunJob
  	fi
  
- 
+
  #####LINK MODE HANDLING#####
  #If symlink is in LINK mode then create symlink
  elif [ "$SYMLINK" = "LINK" ]; then
  	echo "CREATING LINK IN LINK MODE"
  
  	ln -s "$InputPath" "$MoveDir/$ShowFileName.$originalext"     
- 
+       		GenerateTVShowNFO  
+ 		GenerateEpisodeNFO 
+
  #if file was created
  	if [ -L "$MoveDir/$ShowFileName.$originalext" ]; then	
  		echo "Symlink created $MoveDir/$ShowFileName.$originalext">>"$mythicalLibrarian"/output.log
@@ -1186,13 +1225,14 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  
   #Send notification to XBMC, Update Library, Clean Library
  		XBMCAutomate 		
- 
+
  #Move comskip data
   	 	if [ "$CommercialMarkup" = "Created" ]; then
  			mv "$mythicalLibrarian"/markupframes.txt "$MoveDir/$ShowFileName.txt"
  			echo "$MoveDir/$ShowFileName.txt">>"$mythicalLibrarian"/created.tracking
  		fi
  		echo "#mythicalLibrarian '$1' '$2' '$3'">>$mythicalLibrarian/doover.sh
+
  		dailyreport "$ShowFileName"
  		generaterss
    		jobtype=LinkModeSucessful		
@@ -1232,4 +1272,4 @@ test -d $rssDir && checkpermissions "40" "$rssDirFreeSpace" "$rssDir"
  jobtype=GenericUnspecifiedError
  RunJob
 
-Exit 5
+Exit 4
